### ISSUE TITLE
User Account Deletion

### ISSUE THREAD

**Issue by allan1m** [byui-cse397/2024WinCSE490PCP#174]
**Story Description: User Account Deletion**
SRS: 1.1.2. User Account Management
SDD: Back-End Design
Story:
As a user of the community board mobile application, I want to have the ability to delete my account if I no longer wish to be part of the community or if I want to deactivate my account temporarily.

Acceptance Criteria:

**1. Delete Account Functionality:**

- Implement a user-friendly mechanism within the application to allow users to initiate the account deletion process.
- Provide clear instructions and options for users to confirm their decision to delete their account.

**2. Backend Integration**:

- Develop backend API endpoints to handle user account deletion requests securely.
- Ensure that the backend verifies the authenticity of the user initiating the deletion process to prevent unauthorized account deletions.

**3. Data Removal:**

- Delete all user-related data associated with the account from the backend database upon successful account deletion.
- Remove any references or associations of the user account from the system to ensure data privacy and compliance with regulations.

**4. Confirmation and Feedback:**

- Prompt users to confirm their decision before proceeding with the account deletion process.
- Provide informative feedback to users upon successful deletion of their account, confirming the completion of the process.

**5. Graceful Handling of Deletion Errors:**

- Handle potential errors or exceptions that may occur during the account deletion process gracefully.
- Provide informative error messages to users in case of deletion failures or unexpected issues.

**6. Account Deactivation (Optional):**

- Optionally, implement functionality to allow users to deactivate their accounts temporarily instead of permanently deleting them.
- Provide users with the option to reactivate their accounts later if they decide to return to the community.

**7. Testing and Quality Assurance:**

- Develop comprehensive unit tests to validate the functionality of the user account deletion feature.
- Write integration tests to ensure seamless interaction between the frontend and backend components.
- Conduct end-to-end testing to simulate user account deletion scenarios and validate the user experience.

**8. Documentation and Support:**

- Document the account deletion process and associated API endpoints for future reference and maintenance.
- Provide user support and documentation to assist users with the account deletion process if needed.
- Ensure that the account deletion feature aligns with user expectations and usability standards.

Additional Considerations:

- Implement logging and auditing mechanisms to track account deletion requests and ensure accountability.
- Provide users with the option to download their data or export content before initiating the account deletion process.
- Comply with relevant data protection regulations (e.g., GDPR) regarding user data deletion and retention policies.

**Comment by awarbler** [comment]
Test Cases Code .java
import static org.junit.Assert.*;

import java.util.Date;
import org.junit.Test;

public class DeleteUserTest {
  /*
    testValidDeletion:
      Tests if a user account can be successfully deleted with valid deletion
    credentials and confirms that the deletion date is set.
  */

  @Test
  public void testValidDeletion() {
    // Arrange
    long userId = 123;
    String username = "testUser";
    String email = "test@example.com";
    String password = "password123";
    String confirmationPassword = "password123";
    String deletionReason = "Account closure";

    // Act
    DeleteUser deleteUser =
        new DeleteUser(userId, username, email, password, confirmationPassword,
                       deletionReason);
    deleteUser.confirmDeletion();

    // Assert
    assertEquals(deletionReason, deleteUser.getDeletionReason());
    assertNotNull(deleteUser.getDeletionDate());
  }

  /*
    testInvalidPassword:
      Tests if deletion fails when the confirmation password doesn't match the
    user's password.
  */

  @Test
  public void testInvalidPassword() {
    // Arrange
    long userId = 123;
    String username = "testUser";
    String email = "test@example.com";
    String password = "password123";
    String confirmationPassword = "invalidPassword";
    String deletionReason = "Account closure";

    // Act
    DeleteUser deleteUser =
        new DeleteUser(userId, username, email, password, confirmationPassword,
                       deletionReason);

    // Assert
    assertFalse(deleteUser.validateCredentials());
  }

  /*
    testEmptyDeletionReason:
      Tests if deletion fails when the deletion reason is empty.
  */

  @Test
  public void testEmptyDeletionReason() {
    // Arrange
    long userId = 123;
    String username = "testUser";
    String email = "test@example.com";
    String password = "password123";
    String confirmationPassword = "password123";
    String deletionReason = "";

    // Act
    DeleteUser deleteUser =
        new DeleteUser(userId, username, email, password, confirmationPassword,
                       deletionReason);

    // Assert
    assertFalse(deleteUser.validateCredentials());
  }

  /*
    testNullDeletionDateBeforeConfirmation:
      Tests if the deletion date is null before the deletion is confirmed.
  */

  @Test
  public void testNullDeletionDateBeforeConfirmation() {
    // Arrange
    long userId = 123;
    String username = "testUser";
    String email = "test@example.com";
    String password = "password123";
    String confirmationPassword = "password123";
    String deletionReason = "Account closure";

    // Act
    DeleteUser deleteUser =
        new DeleteUser(userId, username, email, password, confirmationPassword,
                       deletionReason);

    // Assert
    assertNull(deleteUser.getDeletionDate());
  }

  /*
    testDeletionDateAfterConfirmation:
      Tests if the deletion date is set after the deletion is confirmed.
  */

  @Test
  public void testDeletionDateAfterConfirmation() {
    // Arrange
    long userId = 123;
    String username = "testUser";
    String email = "test@example.com";
    String password = "password123";
    String confirmationPassword = "password123";
    String deletionReason = "Account closure";

    // Act
    DeleteUser deleteUser =
        new DeleteUser(userId, username, email, password, confirmationPassword,
                       deletionReason);
    deleteUser.confirmDeletion();
    Date deletionDate = deleteUser.getDeletionDate();

    // Assert
    assertNotNull(deletionDate);
  }
}

**Comment by awarbler** [comment]
Examples 

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

abstract class DBTest {
  public void runTest(Connection connection) {
    try {
      if (test(connection)) {
        System.out.println(getClass().getSimpleName() + " passed.");
      } else {
        System.out.println(getClass().getSimpleName() + " failed.");
      }
    } catch (Exception e) {
      System.out.println(getClass().getSimpleName() +
                         " raised an exception: " + e);
    }
  }

  protected abstract boolean test(Connection connection);
}

class TestDeleteAccount extends DBTest {
  @Override
  protected boolean test(Connection connection) {
    int userId = 1;
    return deleteAccount(userId, connection);
  }

  private boolean deleteAccount(int userId, Connection connection) {
    try (PreparedStatement statement = connection.prepareStatement(
             "DELETE FROM accounts WHERE user_id = ?")) {
      statement.setInt(1, userId);
      int rowsAffected = statement.executeUpdate();
      return rowsAffected > 0;
    } catch (SQLException e) {
      System.out.println("Error deleting account: " + e);
      return false;
    }
  }
}

class TestAuthenticationVerification extends DBTest {
  @Override
  protected boolean test(Connection connection) {
    String invalidToken = "invalid_token";
    return !verifyAuthentication(invalidToken);
  }

  private boolean verifyAuthentication(String token) {
    // Simulate token verification
    return token.equals("valid_token");
  }
}

// Similarly, define other test classes following the same pattern

public class Main {
  public static void main(String[] args) {
    try {
      Connection connection = DriverManager.getConnection(
          "jdbc:mysql://localhost:3306/database_name", "username", "password");
      new TestDeleteAccount().runTest(connection);
      // Run other tests similarly
      connection.close();
    } catch (SQLException e) {
      e.printStackTrace();
    }
  }
}
